# Generated by Django 4.2.7 on 2024-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
