# Generated by Django 4.2.7 on 2024-02-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_message'),
        ('pages', '0004_offre_capacite_offre_lieu'),
    ]

    operations = [
    ]
