# Generated by Django 3.2.23 on 2024-02-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_message'),
        ('pages', '0004_offre_capacite_offre_lieu'),
    ]

    operations = [
    ]
